### PR TITLE
Colors

### PR DESCRIPTION
**Pull request by dempfi**

### CODE REVIEW

**Comment by coreyward** [comment]
As an FYI, I dislike several of these changes; having them show up unannounced was unwelcome. I went ahead and installed via git clone and reverted this PR to get the previous behavior back and I won't be maintaining parity with future dev, for what it's worth. 

It would be preferential for significant updates to these colors to be provided alongside the existing colorways. ST2/3 Package Control does not, unfortunately, allow locking to a major version, so typical semantic versioning isn't useful.

**Comment by dempfi** [comment]
Hey @coreyward. I thought this update would be welcome 🙁 Can you please point out what changes you don’t like in particular?

**Comment by coreyward** [comment]
Using Ruby: the “Library function” color highlights a bunch of insignificant methods in red, adding visual noise without providing additional information to me. I don’t need to see that ‘to_hash’ is implemented somewhere in Ruby core, for example. 

Also in Ruby: highlighting instance variables the same as method names breaks the visual hierarchy. I don’t really even like coloring ivars differently than local or block local vars, but if it’s going to happen it should be subtle and not conflict with the method name or constant highlights. 

I’m also not sold on coloring separators differently.

**Comment by dempfi** [comment]
You have a point @coreyward. Highlighting for ruby should be improved. Ruby is one of those languages which are hard to highlight properly, I’ll revisit issues you pointed out in next minor release.

**Pull request merged**
