### PR TITLE
Highlight sidebar row for current item

### PR DESCRIPTION
**Pull request by pzgz**
Using setting `ui_sidebar_highlight_row` to highlight whole row for
current item in sidebar. 

Currently, theme will only show a left heading
highlight for current item, I found myself miss it all the time,
especially when there's horizontal scroll in sidebar, adding this
setting will highlight whole row for current item, and will make you
easier to get current item.

Following is the screenshot for mirage.

mirage

I tried to use current accent and set opacity to `0.08` for less distruption. And I have to changed the `layer1.inner_margin` from `[5, 0, 0, 0]` to `[5, 0, 0, 3]`, to make the left heading be closed to the center of the background.

### CODE REVIEW

**Comment by pzgz** [comment]
@dempfi I have merged your recent updates into this pull request, let me know if there's any concern. Really looking forward for the merge so that I can get back to use package version again. Thanks.

**Comment by dempfi** [comment]
hey @pzgz, thx for contribution and sorry for delay, I'll check locally soon and will either notify you or merge

**Comment by pzgz** [comment]
@dempfi Thanks a lot ^_^

**Comment by breeze-liu** [comment]
It looks very nice

**Comment by dempfi** [comment]
Hi @pzgz sorry for a long delay. I really like the idea and I think with very few changes we can ship this.

1. You have to change [templates](https://github.com/dempfi/ayu/blob/master/src/templates/sublime.ui.json), not the generated themes.
2. I'd prefer to have background color of row as `ui.panel.row_bg` since transparent orange doesn't look good on dark bgs.
3. [optional] To have this changes in ST 2 template too.

---

To build the theme, run `yarn` or `nom install` in `ayu` folder and then use `yarn start` or `npm start` to generate themes while you edit the templates.

**Comment by pzgz** [comment]
Thanks @dempfi for your review. I have revised the commits as you suggested:

1. Yeah, I was changed the `templates`, the generated themes were actually changed by your scripts
2. I have changed the background color to `ui.panel.row_bg.rgb`, and changed the opacity to `1` for highlight one
3. I did changes to the sublimetext2 theme template as well, somehow, I don't have st2 installed, so the problem is I cannot carry out tests on st2 on the result.

**Comment by dempfi** [comment]
thx @pzgz for the contribution 👍

**Pull request merged**
