### PR TITLE
Add link to ayu for VSCode

### PR DESCRIPTION
**Pull request by teabyii**

### CODE REVIEW

**Comment by dempfi** [comment]
This is great @teabyii. I use your port when I work with TS code in VSCode ❤️ and I really like what you did in the port especially with recent change and support of the new workbench styling options, I was going to ping you about that 😄

**Comment by pahen** [comment]
Nice to hear that you liked it @dempfi 😀

**Comment by andriijas** [comment]
@dempfi the colors in sublime feels more "faded" than in vscode where they "glow" a bit more. vscode left, sublime right: https://imgur.com/a/5yS3vX8  is the vscode theme using different colors?

**Comment by dempfi** [comment]
@andriijas that's because same colours are rendered differently in vscode and sublime(different color profiles are used). I'm working on an update for the vscode that also includes color fixes.

**Pull request merged**
