### PR TITLE
Changed foreground color of the current selected match while searching

### PR DESCRIPTION
**Pull request by ankitkhedekar**
Before:
before

After:
after

### CODE REVIEW

**Comment by k15a** [comment]
I think you should change this in one of these files: https://github.com/dempfi/ayu/tree/master/src/templates

Your changed file may change when you run the build script.

**Comment by ankitkhedekar** [comment]
thanks @k15a , didn't notice that.
Will change and update

**Comment by k15a** [comment]
You may checkout the other 2 themes if it's only a problem with the dark color scheme.

**Comment by ankitkhedekar** [comment]
For Light theme its is already white so I don't think it will matter, but will need to change it for Mirage as well I guess.

Also can you guide me with the build process?

**Comment by k15a** [comment]
Yeah I think so. 👍

**Comment by ankitkhedekar** [comment]
Changes done to src template instead to the compiled file

- Added a new key `find_highlight_fg` to all themes. Hex value for this copied the same as `common.bg`
- Used the above key in template instead of hardcoded value

@k15a your thoughts?

**Comment by k15a** [comment]
Yeah looks good 👍

**Comment by dempfi** [comment]
Hi, guys, good that you figured out what should be changed by your own :)

@ankitkhedekar thank you very much for you contribution! 🎉 

Regarding PR:
you also have to change this [yaml syntax file](https://github.com/dempfi/ayu/blob/master/src/templates/sublime.syntax.yml) and compile it using [PackageDev](https://github.com/SublimeText/PackageDev).

* Run command `PackageDev: Convert(YAML, JSON, PLIST) to...`.

Another thing regarding new variable `find_highlight_fg`. I suggest to reuse `common.bg.hex` [here](https://github.com/dempfi/ayu/blob/master/src/templates/sublime.syntax.yml#L21) and move declaration of `white` to next place where it's used, [here](https://github.com/dempfi/ayu/blob/master/src/templates/sublime.syntax.yml#L138) for example.

If you need any help, ask, I'll try to help :)

**Comment by ankitkhedekar** [comment]
@dempfi I am not sure about how the PackageDev compilation works. Will need help.

Any specific command?

**Comment by dempfi** [comment]
@ankitkhedekar 
* open yml file
* open command panel (<kbd>cmd/ctrl</kbd> + <kbd>shift</kbd> + <kbd>p</kbd>)
* paste `PackageDev: Convert(YAML, JSON, PLIST) to`
* hit <kbd>return</kbd>
* copile syntaxes from terminal by `npm run b`

PackageDev will compile xml template for syntax, and from xml template you will compile with `npm run b` actual syntax definitions for each theme(mirage, light and dark)

**Comment by ankitkhedekar** [comment]
@dempfi thanks. I did those steps, but since I had already done those changes manually, no diff is shown.
Hope that is fine?

**Comment by dempfi** [comment]
@ankitkhedekar absolutely, thx again for your contribution ❤️

**Pull request merged**
